name: mattg
favicon: null
layout_spectrum: 0.973010758170858
typography_spectrum: 0.8731467784382403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12977935769595206
  lightness: 0.6403346213046461
  saturation: 0.6003343120682985
  rhythmicContrast: 0.9453636852558702
purpose: []
