name: mjg
favicon: null
layout_spectrum: 0.973010758170858
typography_spectrum: 0.8731467784382403
title: mjg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7df'
    - '#7e8ec1'
    - '#5162a8'
    - '#c3b0a2'
    - '#54372f'
  brandStrength: 0.1875
  lightness: 0.6403346213046461
  saturation: 0.6003343120682985
  rhythmicContrast: 0.9453636852558702
purpose: []
